### ISSUE TITLE
Training with resized input image?

### ISSUE THREAD

**Issue by Archerwz** [mileyan/AnyNet#11]
Hi, I was wondering if I train the model with resized input instead of cropped input, will it affect the model that much? If I resize the input image, do I need to scale the ground truth disparity maps or I just resize it directly without further operation?

**Comment by mileyan** [comment]
I have not tested it yet, but it should be ok to do the resizing augmentation. You have to scale the ground truth disparity as long as you resize the input image. One more suggestion is because of the sparse depth map of KITTI, bilinear is not feasible here. You can use maxpooling to do downsample and use nearest mode to do upsample.
